import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import StoreThemeProvider from "../providers/StoreThemeProvider";
import { fetchStoreByDomain, fetchStoreConfig } from "../lib/api";
import { headers } from "next/headers";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Dynamic store resolution based on domain
  const headersList = await headers();
  const domain = headersList.get('host') || 'localhost:3000';

  // Clean domain (remove port if needed for DB lookup, though our backend handles local ports now)
  // But usually in prod it's just the domain. For localhost dev, we might want to strip port 
  // if we save 'localhost' in DB but access via 'localhost:3000'

  let store = await fetchStoreByDomain(domain);

  // Fallback for development if strict domain match fails (e.g. localhost vs localhost:3000)
  if (!store && domain.includes('localhost')) {
    const fallbackId = '675bd1d5334c9f136d8849b2'; // Dev Fallback
    store = await fetchStoreConfig(fallbackId);
  }

  const themeConfig = store?.theme;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreThemeProvider themeConfig={themeConfig}>
          {children}
        </StoreThemeProvider>
      </body>
    </html>
  );
}
